#!/usr/bin/env ruby
#^syntax detection

site "https://galaxy.ansible.com/api/v1"

role "ansible-docker",
  github: "AnsibleShipyard/ansible-docker"
role "ansible-java8",
  github: "mhamrah/ansible-java8"
role "ansible-zookeeper",
  github: "andreimc/ansible-zookeeper"
role "ansible-marathon",
  github: "AnsibleShipyard/ansible-marathon"
role "ansible-mesos",
  github: "AnsibleShipyard/ansible-mesos"
role "ansible-consul",
  github: "jivesoftware/ansible-consul"
role "franklinkim.nginx",
  github: "weareinteractive/ansible-nginx"
role "franklinkim.openssl",
  github: "weareinteractive/ansible-openssl"
role "franklinkim.htpasswd",
  github: "weareinteractive/ansible-htpasswd"
